language: java
jdk:
- openjdk12

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle

sudo: true

services:
  - postgresql

addons:
  sonarcloud:
    organization: "euiagosilva"
    token:
      secure: "2851657440ed74a5664be1b5cf2765f272f2f460"
  postgresql: 9.6

before_script:
  - psql -c 'create database discback_db;' -U postgres

script:
  - ./gradlew sonarqube