version: '3.5'

services:
  discback-db:
    image: postgres:11
    networks:
      - discback-db-network
    restart: always
    ports:
      - 5432:5432
    volumes:
      - /tmp/postgres/discback-db/data:/var/lib/postgresql/data
    container_name: discback-db
    environment:
      POSTGRES_DB: discback_db
      POSTGRES_PASSWORD: secret

networks:
  discback-db-network:
    driver: bridge